name: CI

on:
  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  setup:
    uses: ./.github/workflows/setup.yml
    with:
      BUILD_ENV: production
    secrets: inherit
  
  lint:
    needs: [setup]
    uses: ./.github/workflows/lint.yml
    with:
      BUILD_ENV: production
    secrets: inherit

  build-dependencies:
    needs: [setup]
    uses: ./.github/workflows/dependencies.yml
    with:
      BUILD_ENV: production
    secrets: inherit

  unit-tests:
    needs: [build-dependencies]
    uses: ./.github/workflows/unit-tests.yml
    with:
      BUILD_ENV: production
    secrets: inherit

  build-sso:
    needs: [unit-tests]
    uses: ./.github/workflows/projects.yml
    with:
      ENVIRONMENT: SSO
      BUILD_ENV: production
      PATH: dist
      PROJECT: sso
      COMMAND: build
    secrets: inherit

  build-manager:
    needs: [unit-tests]
    uses: ./.github/workflows/projects.yml
    with:
      ENVIRONMENT: MANAGER
      BUILD_ENV: production
      PATH: dist
      PROJECT: manager
      COMMAND: build
    secrets: inherit
  